name: another_movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  webview_flutter: any

  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  get: ^4.6.6
  gap: ^3.0.1
  cached_network_image: ^3.3.1
  video_player: ^2.8.2
  player:
    path: player
  # http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
